// Seed data for demo API
// Initial parts data that covers all categories, statuses, and types

export const seedParts = [
    // REVIEW CATEGORY - Parts waiting for approval
    {
        id: 1,
        type: "cnc",
        material: "Aluminum 6061",
        part_id: "FRAME-001",
        name: "Main Frame Bracket",
        subsystem: "Frame",
        assigned: null,
        status: "Pending",
        misc_info: null,
        notes: "New design for reinforced mounting points",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/123456789",
        claimed_date: null,
        created_at: "2024-12-15T08:00:00Z",
        updated_at: "2024-12-15T08:00:00Z",
        category: "review",
        amount: 2,
    },
    {
        id: 2,
        type: "hand",
        material: "Steel",
        part_id: "ARM-002",
        name: "Control Arm Linkage",
        subsystem: "Suspension",
        assigned: null,
        status: "Pending",
        misc_info: null,
        notes: "Replace worn linkage from previous season",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/987654321",
        claimed_date: null,
        created_at: "2024-12-14T14:30:00Z",
        updated_at: "2024-12-14T14:30:00Z",
        category: "review",
        amount: 1,
    },
    {
        id: 3,
        type: "cnc",
        material: "Delrin",
        part_id: "GEAR-003",
        name: "Drive Gear Housing",
        subsystem: "Drivetrain",
        assigned: null,
        status: "Pending",
        misc_info: null,
        notes: "Optimize for weight reduction",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/456789123",
        claimed_date: null,
        created_at: "2024-12-13T10:15:00Z",
        updated_at: "2024-12-13T10:15:00Z",
        category: "review",
        amount: 3,
    },

    // CNC CATEGORY - Parts approved for CNC machining
    {
        id: 4,
        type: "cnc",
        material: "Aluminum 7075",
        part_id: "PLATE-004",
        name: "Motor Mount Plate",
        subsystem: "Power",
        assigned: "Alice Johnson",
        status: "In Progress",
        misc_info: null,
        notes: "High-strength mounting for brushless motors",
        file: "PLATE-004.step",
        onshape_url: "https://cad.onshape.com/documents/789123456",
        claimed_date: "2024-12-12T09:00:00Z",
        created_at: "2024-12-11T16:45:00Z",
        updated_at: "2024-12-12T09:00:00Z",
        category: "cnc",
        amount: 4,
    },
    {
        id: 5,
        type: "cnc",
        material: "Steel",
        part_id: "SHAFT-005",
        name: "Drive Shaft",
        subsystem: "Drivetrain",
        assigned: "Bob Smith",
        status: "In Progress",
        misc_info: null,
        notes: "Precision machined shaft with keyway",
        file: "SHAFT-005.step",
        onshape_url: "https://cad.onshape.com/documents/321654987",
        claimed_date: "2024-12-10T11:30:00Z",
        created_at: "2024-12-09T13:20:00Z",
        updated_at: "2024-12-10T11:30:00Z",
        category: "cnc",
        amount: 2,
    },
    {
        id: 6,
        type: "cnc",
        material: "Brass",
        part_id: "BUSHING-006",
        name: "Pivot Bushing",
        subsystem: "Suspension",
        assigned: null,
        status: "Already Started",
        misc_info: null,
        notes: "Low-friction brass bushing for smooth operation",
        file: "BUSHING-006.step",
        onshape_url: "https://cad.onshape.com/documents/654987321",
        claimed_date: null,
        created_at: "2024-12-08T15:10:00Z",
        updated_at: "2024-12-08T15:10:00Z",
        category: "cnc",
        amount: 6,
    },
    {
        id: 17,
        type: "cnc",
        material: "Titanium",
        part_id: "ARMOR-017",
        name: "Armor Plate",
        subsystem: "Frame",
        assigned: null,
        status: "Reviewed",
        misc_info: null,
        notes: "Lightweight titanium armor plating for protection",
        file: "ARMOR-017.step",
        onshape_url: "https://cad.onshape.com/documents/369258147",
        claimed_date: null,
        created_at: "2024-12-07T12:30:00Z",
        updated_at: "2024-12-07T12:30:00Z",
        category: "cnc",
        amount: 2,
    },

    // HAND CATEGORY - Parts approved for hand fabrication
    {
        id: 7,
        type: "hand",
        material: "Aluminum",
        part_id: "BRACKET-007",
        name: "Sensor Bracket",
        subsystem: "Electronics",
        assigned: "Charlie Wilson",
        status: "In Progress",
        misc_info: {
            handWorkers: [
                {
                    name: "Charlie Wilson",
                    timestamp: "2024-12-07T14:00:00Z",
                },
            ],
        },
        notes: "Custom bracket for ultrasonic sensors",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/147258369",
        claimed_date: "2024-12-07T14:00:00Z",
        created_at: "2024-12-06T12:30:00Z",
        updated_at: "2024-12-07T14:00:00Z",
        category: "hand",
        amount: 1,
    },
    {
        id: 8,
        type: "hand",
        material: "Steel",
        part_id: "ROD-008",
        name: "Push Rod",
        subsystem: "Suspension",
        assigned: "Diana Davis",
        status: "In Progress",
        misc_info: {
            handWorkers: [
                {
                    name: "Diana Davis",
                    timestamp: "2024-12-05T10:45:00Z",
                },
            ],
        },
        notes: "Adjustable length push rod assembly",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/963852741",
        claimed_date: "2024-12-05T10:45:00Z",
        created_at: "2024-12-04T09:15:00Z",
        updated_at: "2024-12-05T10:45:00Z",
        category: "hand",
        amount: 2,
    },
    {
        id: 9,
        type: "hand",
        material: "Plastic",
        part_id: "COVER-009",
        name: "Battery Cover",
        subsystem: "Power",
        assigned: null,
        status: "Reviewed",
        misc_info: null,
        notes: "Protective cover for battery compartment",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/852741963",
        claimed_date: null,
        created_at: "2024-12-03T16:20:00Z",
        updated_at: "2024-12-03T16:20:00Z",
        category: "hand",
        amount: 1,
    },
    {
        id: 10,
        type: "hand",
        material: "Wood",
        part_id: "TEMPLATE-010",
        name: "Drill Template",
        subsystem: "Assembly",
        assigned: "Eve Garcia",
        status: "In Progress",
        misc_info: {
            handWorkers: [
                {
                    name: "Eve Garcia",
                    timestamp: "2024-12-02T13:30:00Z",
                },
            ],
        },
        notes: "Precision drilling template for consistent holes",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/741963852",
        claimed_date: "2024-12-02T13:30:00Z",
        created_at: "2024-12-01T11:00:00Z",
        updated_at: "2024-12-02T13:30:00Z",
        category: "hand",
        amount: 1,
    },

    // COMPLETED CATEGORY - Finished parts
    {
        id: 11,
        type: "cnc",
        material: "Aluminum 6061",
        part_id: "SPACER-011",
        name: "Bearing Spacer",
        subsystem: "Drivetrain",
        assigned: "Alice Johnson",
        status: "Completed",
        misc_info: null,
        notes: "Precision spacer for wheel bearings",
        file: "SPACER-011.step",
        onshape_url: "https://cad.onshape.com/documents/369258147",
        claimed_date: "2024-11-28T08:30:00Z",
        created_at: "2024-11-25T14:45:00Z",
        updated_at: "2024-11-30T16:20:00Z",
        category: "completed",
        amount: 8,
    },
    {
        id: 12,
        type: "cnc",
        material: "Steel",
        part_id: "PIN-012",
        name: "Hitch Pin",
        subsystem: "Frame",
        assigned: "Bob Smith",
        status: "Completed",
        misc_info: null,
        notes: "Locking hitch pin for trailer connection",
        file: "PIN-012.step",
        onshape_url: "https://cad.onshape.com/documents/258147369",
        claimed_date: "2024-11-26T09:15:00Z",
        created_at: "2024-11-24T10:30:00Z",
        updated_at: "2024-11-29T15:45:00Z",
        category: "completed",
        amount: 2,
    },
    {
        id: 13,
        type: "hand",
        material: "Aluminum",
        part_id: "CLAMP-013",
        name: "Cable Clamp",
        subsystem: "Electronics",
        assigned: "Charlie Wilson",
        status: "Completed",
        misc_info: {
            handWorkers: [
                {
                    name: "Charlie Wilson",
                    timestamp: "2024-11-23T11:00:00Z",
                },
                {
                    name: "Diana Davis",
                    timestamp: "2024-11-25T14:30:00Z",
                },
            ],
        },
        notes: "Custom clamp for securing power cables",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/147369258",
        claimed_date: "2024-11-23T11:00:00Z",
        created_at: "2024-11-20T15:20:00Z",
        updated_at: "2024-11-28T12:10:00Z",
        category: "completed",
        amount: 3,
    },
    {
        id: 14,
        type: "hand",
        material: "Steel",
        part_id: "HINGE-014",
        name: "Access Panel Hinge",
        subsystem: "Frame",
        assigned: "Eve Garcia",
        status: "Completed",
        misc_info: {
            handWorkers: [
                {
                    name: "Eve Garcia",
                    timestamp: "2024-11-21T10:45:00Z",
                },
            ],
        },
        notes: "Heavy-duty hinge for maintenance access",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/963741852",
        claimed_date: "2024-11-21T10:45:00Z",
        created_at: "2024-11-18T13:15:00Z",
        updated_at: "2024-11-27T17:30:00Z",
        category: "completed",
        amount: 4,
    },
    {
        id: 15,
        type: "cnc",
        material: "Delrin",
        part_id: "ROLLER-015",
        name: "Idler Roller",
        subsystem: "Conveyor",
        assigned: "Alice Johnson",
        status: "Completed",
        misc_info: null,
        notes: "Low-friction roller for belt system",
        file: "ROLLER-015.step",
        onshape_url: "https://cad.onshape.com/documents/852369741",
        claimed_date: "2024-11-19T12:30:00Z",
        created_at: "2024-11-15T09:45:00Z",
        updated_at: "2024-11-26T14:15:00Z",
        category: "completed",
        amount: 6,
    },
    {
        id: 16,
        type: "hand",
        material: "Plastic",
        part_id: "GUIDE-016",
        name: "Cable Guide",
        subsystem: "Electronics",
        assigned: "Diana Davis",
        status: "Completed",
        misc_info: {
            handWorkers: [
                {
                    name: "Diana Davis",
                    timestamp: "2024-11-17T14:20:00Z",
                },
                {
                    name: "Charlie Wilson",
                    timestamp: "2024-11-20T16:45:00Z",
                },
            ],
        },
        notes: "3D printed guide for cable routing",
        file: null,
        onshape_url: "https://cad.onshape.com/documents/741852963",
        claimed_date: "2024-11-17T14:20:00Z",
        created_at: "2024-11-14T11:30:00Z",
        updated_at: "2024-11-25T13:50:00Z",
        category: "completed",
        amount: 2,
    },
];
